### ISSUE TITLE
Cant parse some characters in the password field

### ISSUE THREAD

**Issue by Theraga** [ferreira-igor/micropython-wifi_manager#4]
I have noticed that if I include some special characters in the password (Like @ and + ) the connection attempt will be aborted.
This is because only certain characters are replaced on line 215. Is it possible to include more characters?. 

We used the solutions provided in the first post here: https://forum.micropython.org/viewtopic.php?t=3076 . Making a ton of replaces could also work but that doesn't look very elegant.

**Comment by ferreira-igor** [comment]
> I have noticed that if I include some special characters in the password (Like @ and + ) the connection attempt will be aborted. This is because only certain characters are replaced on line 215. Is it possible to include more characters?.
> 
> We used the solutions provided in the first post here: https://forum.micropython.org/viewtopic.php?t=3076 . Making a ton of replaces could also work but that doesn't look very elegant.

Thanks for the tip!

The update is already implemented.
